development:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: widb_development
  username: dunice
  password: dunice

test:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: widb_test
  username: dunice
  password: dunice
